version: '3.8'

services:
  saaslab_db_image:
    container_name: saaslab_db_image
    image: postgres:15.7
    restart: always

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    
    ports:
      - '3874:5432'
    
    volumes:
      - saas_db_volume:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  saas_db_volume:
    driver: local