version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=saas-boilerplate
    ports:
      - '27017:27017'
    volumes:
      - saas-boilderplate-db:/data/db

volumes:
  saas-boilderplate-db:
    driver: local